# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ for more details
#

version: 2
jobs:
  # Deploy to production site
  # Note that we need a custom SSH config to let rsync know
  # how to reach the production site.
  deploy-production:
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - run: mkdir -p ~/.ssh
      - run: echo $TEAMDIGITALE_SSH_CONF | base64 -d > ~/.ssh/config
      - run: echo $TEAMDIGITALE_SSH_KNOWN_HOSTS | base64 -d > ~/.ssh/known_hosts
      - run: which rsync || sudo apt-get install rsync
      #- run: rsync -avP --rsync-path="sudo -u www-data rsync" docs-italia/ developers.italia.it:/data/www/docs.developers.italia.it/web/
      - run: ls -lah .
      
workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              only:
                - master
      - deploy-production:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
